### ISSUE TITLE
STA9750 CristelKZuniga MiniProject #00

### ISSUE THREAD

**Issue by CristelKZuniga** [CristelKZuniga/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://cristelkzuniga.github.io/STA9750-2024-FALL/

Thank you!

**Comment by michaelweylandt** [comment]
Thanks @CristelKZuniga !

Peer Feedback:

- @Will-Peters
- @haolinnn
- @velasco23

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @CristelKZuniga.

Website URL should be: https://CristelKZuniga.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @CristelKZuniga and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by velasco23** [comment]
@CristelKZuniga Hi Kassandra, I was able to access your website successfully. You did a great job at building the site. I like your theme! 

My suggestion would be to add a picture if possible.

**Comment by Will-Peters** [comment]
@CristelKZuniga Hi Kassandra, I liked the fun take on the welcome to the website, great header/introduction

A recommendation would be to link the kzuniga and just check if the header should be portafolio or portfolio

**Comment by haolinnn** [comment]
@CristelKZuniga Hi Kassandra, good work! I like the header and theme. I think it is better if the contact information is italic.
